FlatBuffers post
alexpusch/blog pull request #4
Opened 2016-11-23 18:25 UTC by alexpusch

2016-11-24 04:48 UTC, BlueHotDog reviewed
very awesome!

2016-11-24 04:48 UTC, BlueHotDog commented on flatbuffers/flatbuffers_case_study.md
> +Data serialization is very common process in web application. So common that no one thinks of it. You just pull data from the DB, and your server and client frameworks just handle this thing for you.
the first sentence reads weird..
maybe:
Data serialization is a very common process in web applications

2016-11-24 04:48 UTC, BlueHotDog commented on flatbuffers/flatbuffers_case_study.md
> +Data serialization is very common process in web application. So common that no one thinks of it. You just pull data from the DB, and your server and client frameworks just handle this thing for you.
I think a lot of the benefit are related to data de-serialization as well.

2016-11-24 04:48 UTC, BlueHotDog commented on flatbuffers/flatbuffers_case_study.md
> +A possible solution for this scaling issue are FlatBuffers. We've utilized this tool to do our heavy lifting and lived to tell about it.
is Flatbuffers? it's a single technology

2016-11-24 04:48 UTC, BlueHotDog commented on flatbuffers/flatbuffers_case_study.md
> +# What are FlatBuffers?
Flatbuffer vs other solutions?

2016-11-24 04:48 UTC, BlueHotDog commented on flatbuffers/flatbuffers_case_study.md
> +Case study of Javascript Flat Buffers
seems this is more of a flatbuffer vs json post and should gain more traffic

2016-11-24 04:48 UTC, BlueHotDog commented on flatbuffers/flatbuffers_case_study.md
> +After defining the schema, we run the flatbuffer 'compiler' - flatc. This generates code in our language of choice. That code handles all the bytes and bits calculation flatbuffer is based on.
one thing to mention is that flatbuffer are available to a LOT of languages aside from js

2016-11-24 04:48 UTC, BlueHotDog commented on flatbuffers/flatbuffers_case_study.md
> +This undertaking raises many challenges, one of which is to transfer all of those events from the recorded user to our servers, and from our servers to the player. The efficiency of this process is m
I would also add a background check we did of FB vs other similar frameworks we did and why we chose flatbuffers..

2016-11-24 04:48 UTC, BlueHotDog commented on flatbuffers/flatbuffers_case_study.md
> +As you can see, Flatbuffers creation and reading is not trivial. The API is verbal and cumbersome.
maybe talk about actual cons? like no typesafe, building is form the outside in

2016-11-24 04:48 UTC, BlueHotDog commented on flatbuffers/flatbuffers_case_study.md
> +* Lack of streaming support
I would write a conclusion
And also touch put in the benchmarks speed comparison.

2016-11-24 08:19 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +Data serialization is very common process in web application. So common that no one thinks of it. You just pull data from the DB, and your server and client frameworks just handle this thing for you.
👍

2016-11-24 08:20 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +A possible solution for this scaling issue are FlatBuffers. We've utilized this tool to do our heavy lifting and lived to tell about it.
👍

2016-11-24 08:20 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +This undertaking raises many challenges, one of which is to transfer all of those events from the recorded user to our servers, and from our servers to the player. The efficiency of this process is m
did we do that? what were the conclusions?

2016-11-24 08:23 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +After defining the schema, we run the flatbuffer 'compiler' - flatc. This generates code in our language of choice. That code handles all the bytes and bits calculation flatbuffer is based on.
I've added it to the introduction

2016-11-24 08:24 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +As you can see, Flatbuffers creation and reading is not trivial. The API is verbal and cumbersome.
good point. I have a drawbacks section at the bottom, I'll add these points

2016-11-24 17:28 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +* Lack of streaming support
👍

2016-11-28 10:21 UTC, itayadler requested changes

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +Refactoring our entire flow from JSON to FlatBuffers is quite a feat. It's a architecture crossing change that will be dangerous to try and accomplish in one go. We've considered this issue for a whi
redactor => refactor

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +## Flat buffers Example
Flat buffers => FlatBuffers
I think this should be consistent in the entire article

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +The main goal of FlatBuffers is to avoid deseriazation what so ever. This is achieved by defining a binary data protocol - a well defined method to convert data to, and from binary. The binary struct
deseriazation => deserialization

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +This won't be a FlatBuffers tutorial, but to give you a feel for what it's like lets took on a simplified version of our data model.
took on => look at

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +After defining the schema, we run the flatbuffer 'compiler' - flatc. This generates code in our language of choice. That code handles all the bytes and bits calculation flatbuffer is based on.
flatbuffer => FlatBuffers

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +As you can see, Flatbuffers creation and reading is not trivial. The API is verbal and cumbersome.
Flatbuffers => FlatBuffers

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +We began in transforming our recorder messages to FlatBuffers. The recorder creates and send the recorded events as FlatBuffers. The first step of the processing pipeline is to transform the binary d
send => seds

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +## Space banchmark
Space banchmark => Storage size benchmark

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +The next important benchmark would be data availability speed. By this I mean the duration of time it takes from initial request to complete data availability. In this benchmark we will take several
several session => several sessions

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +As expected, JSON is impeded by the parsing stage. FlatBuffers allows immediate access to data after download. Those several seconds of JSON parsing are critical for us. These are the first seconds o
`These are the first seconds of our page loads, where the first impression of our system takes place.`
something is off with this sentence

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +# Conclusion
we pretty pleased => we are pretty pleased

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +This was not an easy ride. There are several caveats in FlatBuffers that gets exaggerated by JavaScatips weak typing nature.
JavaScatips => Javacript's

2016-11-28 10:21 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +FlatBuffer is heavy machinery. It won't do you any good if you don't have a vast number of objects to throw at it.
FlatBuffer => FlatBuffers ?

2016-11-29 08:32 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +Case study of Javascript Flat Buffers
You're right, but the post talks about our specific experience. What about "Refactoring JSON to FlatBuffers", "Moving from JSON to FlatBuffers", "Case study of JSON to FlatBuffers transition". Any ideas?

2016-11-29 08:38 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +Case study of Javascript Flat Buffers
I like Refactoring JSON to FlatBuffers

2016-11-29 08:50 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +The main goal of FlatBuffers is to avoid deseriazation what so ever. This is achieved by defining a binary data protocol - a well defined method to convert data to, and from binary. The binary struct
done

2016-11-29 08:50 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +## Flat buffers Example
done

2016-11-29 08:50 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +This won't be a FlatBuffers tutorial, but to give you a feel for what it's like lets took on a simplified version of our data model.
done

2016-11-29 08:50 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +After defining the schema, we run the flatbuffer 'compiler' - flatc. This generates code in our language of choice. That code handles all the bytes and bits calculation flatbuffer is based on.
done

2016-11-29 08:50 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +As you can see, Flatbuffers creation and reading is not trivial. The API is verbal and cumbersome.
done

2016-11-29 08:50 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +Refactoring our entire flow from JSON to FlatBuffers is quite a feat. It's a architecture crossing change that will be dangerous to try and accomplish in one go. We've considered this issue for a whi
done

2016-11-29 08:50 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +We began in transforming our recorder messages to FlatBuffers. The recorder creates and send the recorded events as FlatBuffers. The first step of the processing pipeline is to transform the binary d
done

2016-11-29 08:50 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +## Space banchmark
done

2016-11-29 08:50 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +The next important benchmark would be data availability speed. By this I mean the duration of time it takes from initial request to complete data availability. In this benchmark we will take several
done

2016-11-29 08:51 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +As expected, JSON is impeded by the parsing stage. FlatBuffers allows immediate access to data after download. Those several seconds of JSON parsing are critical for us. These are the first seconds o
how do you think it should be?

2016-11-29 08:51 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +# Conclusion
done

2016-11-29 08:51 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +This was not an easy ride. There are several caveats in FlatBuffers that gets exaggerated by JavaScatips weak typing nature.
done

2016-11-29 08:51 UTC, alexpusch commented on flatbuffers/flatbuffers_case_study.md
> +FlatBuffer is heavy machinery. It won't do you any good if you don't have a vast number of objects to throw at it.
done

2016-11-29 08:53 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +We began in transforming our recorder messages to FlatBuffers. The recorder creates and send the recorded events as FlatBuffers. The first step of the processing pipeline is to transform the binary d
bah seds :) I mean't sends

2016-11-29 08:59 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +As expected, JSON is impeded by the parsing stage. FlatBuffers allows immediate access to data after download. Those several seconds of JSON parsing are critical for us. These are the first seconds o
Those several seconds of JSON parsing are critical for us. These are the first seconds of our page loads, where the first impression of our system takes place. 
=>
The time spent on JSON parsing during page load time is noticeable when dealing with a higher volume of data, and if we can shave it off, then that'll be key to delivering a non-janky experience to our users.

What do you think?

2016-11-29 09:01 UTC, itayadler requested changes

2016-11-29 09:01 UTC, itayadler commented on flatbuffers/flatbuffers_case_study.md
> +## storage benchmark
Captial S

2017-11-11 11:01 UTC, merged